* Chapter 01
* Lesson 3.1

# Dirac's Bra-Ket Notation

<br>

* [Linear algebra for quantum mechanics](https://furnstahl.github.io/7501-JB/notebooks/Reference/linear_algebra_for_QM.html)
* [amcdawes/QMlabs](https://github.com/amcdawes/QMlabs)
* [Welcome to Chemistry Lessons Using Jupyter Notebooks](https://mccullaghlab.github.io/intro.html)
* [Solving 1-D Schrodinger Equation in Python](https://blog.gwlab.page/solving-1-d-schrodinger-equation-in-python-dcb3518ce454)

Dirac's Bra-Ket notation is a mathematical framework introduced by English physicist Paul Dirac as a compact way to describe quantum states and their transformations. 

Let's see a short example of what bra-ket notation actually does. Imagine a wave function $\psi$ which describes a quantum state of a particle. A median value of coordinate $\vec{r}$ (ecpected value of the position operator) of that particle could be wtitten in the following form:

\begin{equation}
\braket{\hat{r}} = \int_{-\infin}^{\infin} \psi^{*} r \psi dr
\end{equation}

Even a simple requirement such as this is very tidious to write. This is where Dirac's bre-ket notataion comes in handy. The expression from above can be written in a more compact and elegant form using bre-ket notataion:

\begin{align*}
\braket{\hat{r}} = \bra{\psi} r \ket{\psi}
\end{align*}


The main components of the bra-ket notation are **ket** and **bra** operators:

* A **ket** represents a quantum state $\ket{\psi}$. It is a column vector in a complex vector space (Hilbert space).

    \begin{align*}
    \ket{\psi} =
    \begin{bmatrix}
    \psi_1 \\
    \psi_2 \\
    \vdots \\
    \psi_n
    \end{bmatrix}
    \end{align*}
    
    Where $\psi_1$, $\psi_2$ ...$\psi_n$ are column vector components.

* A **bra** $\bra{\psi}$ is the Hermitian conjugate (complex conjugate transpose) of a **ket**:

    \begin{align*}
    \bra{\psi} =
    \begin{bmatrix}
    \psi_1^* & \psi_2^* & \cdots & \psi_n^*
    \end{bmatrix}
    \end{align*}

    Where $\psi_1$, $\psi_2$ ...$\psi_n$ are vector components.

### Python Example

In [2]:
import numpy as np

In [3]:
# Ket |ψ⟩
ket_psi = np.array([[1 + 2j], [3 + 4j]])

print("Ket |ψ⟩:\n")
print(ket_psi)


Ket |ψ⟩:

[[1.+2.j]
 [3.+4.j]]


In [4]:
# Bra ⟨ψ|
bra_psi = ket_psi.conj().T  # Conjugate transpose of |ψ⟩

print("Bra ⟨ψ|:\n")
print(bra_psi)

Bra ⟨ψ|:

[[1.-2.j 3.-4.j]]


In [5]:
# Ket |ψ⟩
ket_psi2 = bra_psi.conj().T  # Conjugate transpose of ⟨ψ|

print("Ket |ψ>:\n")
print(ket_psi2)

Ket |ψ>:

[[1.+2.j]
 [3.+4.j]]


As we can see, bras are created and transposed conjugates of kets and vice versa. It is called adjoint or Hermitian adjoint. In quantum mechanics is often represented using the $\dagger$ symbol.

\begin{align*}
  \bra{\psi} &= \ket{\psi}^{\dagger} \\
  \ket{\psi} &= \bra{\psi}^{\dagger}
\end{align*}

## Inner Product

Inner product of operators represents the overlap or probability amplitude between two quantum states, $\ket{\psi}$ and $\ket{\phi}$. 

* In mathematics, this is a simple dot product:

    \begin{equation}
    \bra{\phi} \ket{\psi} = \braket{\phi|\psi} = \sum_{i} \phi_{i}^{*} \psi_{i}
    \end{equation}

* In quantum mechanics, squared inner product (Born rule) $\left\lvert \braket{\phi|\psi} \right\rvert^{2}$ gives the probability of measuring $\psi$ in state $\phi$.

In [6]:
inner_product = np.dot(bra_psi, ket_psi)

print("Inner Product ⟨ψ|ψ⟩:", inner_product)

Inner Product ⟨ψ|ψ⟩: [[30.+0.j]]


In [7]:
squared_inner_product = np.abs(inner_product)**2  # Square of the magnitude

print("Squared Inner Product |⟨ψ|φ⟩|^2:", squared_inner_product)

Squared Inner Product |⟨ψ|φ⟩|^2: [[900.]]


#### A quick example of what this actually means in a non-quantum world

In [8]:
# Measuring alignment between viewer preferences and the movie profile

# Viewer preference vector (state |ψ⟩)
ket_psi_m = np.array([[0.8 + 0.0j], [0.6 + 0.0j]])  # User likes action 80% and comedy 60% (these are not actual percentages, but action and comedy vector amlitudes)

# Movie profile vector (state |φ⟩)
ket_phi_m = np.array([[0.9 + 0.0j], [0.4 + 0.0j]])  # A movie contains 90% action and 40% comedy (these are not actual percentages, but action and comedy vector amlitudes)

# Conjugate transpose for bra ⟨ψ|
bra_psi_m = ket_psi_m.conj().T

# Inner product
inner_product_m = np.dot(bra_psi_m, ket_phi_m)

# Squared inner product (probability)
squared_inner_product_m = np.abs(inner_product_m)**2

# Output
print("Inner Product ⟨ψ|φ⟩:", inner_product_m)
print("Squared Inner Product |⟨ψ|φ⟩|^2:", squared_inner_product_m)


Inner Product ⟨ψ|φ⟩: [[0.96+0.j]]
Squared Inner Product |⟨ψ|φ⟩|^2: [[0.9216]]


We can be 92% confident that the viewer would like this movie.

In [9]:
# Proof that percentages from above are not nonsence:

print(np.abs(np.dot(ket_psi_m.conj().T, ket_psi_m))**2)
print(np.abs(np.dot(ket_phi_m.conj().T, ket_phi_m))**2)

[[1.]]
[[0.9409]]


Since the squared inner product of the viewer preferences equalt 1, it means the viewer likes exclusively action and comedy. On the other hand, the movie contains $94\%$ of action and comedy, which means there might be components of drama, triller or sci-fi as well.

### Normalization

If the squared inner product of a quantum state vector $\ket{\psi}$ with itself is equal to 1:

\begin{equation}
\left\lvert \braket{\psi|\psi} \right\rvert^{2} = \left\lvert \sum_{i} \psi_{i}^{*} \psi_{i} \right\rvert^{2} = 1
\end{equation}

means the states are normalized.

In [10]:
print("Ket |ψ⟩:\n")
print(ket_psi)

Ket |ψ⟩:

[[1.+2.j]
 [3.+4.j]]


In [11]:
print("squared inner product: ", np.abs(np.dot(ket_psi.conj().T, ket_psi))**2)

squared inner product:  [[900.]]


This means the quantum state is not normalized. It can be normalized by dividing by the norm of $\ket{\psi}$:

\begin{equation}
\ket{\psi_{normalized}}  = \frac{\ket{\psi}}{2}
\end{equation}

Where

\begin{equation}
\|\psi\|  = \sqrt{\braket{\psi|\psi}}
\end{equation}

In [12]:
ket_psi_norm = ket_psi/np.linalg.norm(ket_psi)

ket_psi_norm

array([[0.18257419+0.36514837j],
       [0.54772256+0.73029674j]])

In [13]:
np.abs(np.dot(ket_psi_norm.conj().T, ket_psi_norm))**2

array([[1.]])

The quantum state is now normalized.

### Orthogonality

Two states are orthogonal when their state vectors (kets) are perpendicular to each other in a complex vector space. This means their inner product is zero:

\begin{equation}
\braket{\phi|\psi} = \sum_{i} \phi_{i}^{*} \psi_{i} = 0
\end{equation}

In integral form:

\begin{equation}
\braket{\phi|\psi} =  \int_{-\infin}^{\infin} \phi^{*}(r) \psi(r) dr = 0
\end{equation}

Orthogonal states $\ket{\phi}$ and $\ket{\psi}$ are mutually exclusive. In quantum mechanics it means if a quantum system is in state $\ket{\psi}$ the probability of measuring it in state $\ket{\phi}$ is 0. In summary, these two states are independent and distinguishable.

Imagine two qubits $\ket{0}$ and $\ket{1}$:

\begin{align*}
\ket{0} =
\begin{bmatrix}
1 \\
0
\end{bmatrix}
\end{align*}

\begin{align*}
\ket{1} =
\begin{bmatrix}
0 \\
1
\end{bmatrix}
\end{align*}


In [14]:
# Define the basis states
ket_0 = np.array([[1], [0]])  # |0⟩
ket_1 = np.array([[0], [1]])  # |1⟩

# Compute the inner product ⟨0|1⟩
inner_product = np.dot(ket_0.conj().T, ket_1)

# Output the result
print("⟨0|1⟩ =", inner_product)

⟨0|1⟩ = [[0]]


This means they are orthogonal:

\begin{equation}
\braket{0|1} = 0
\end{equation}

In reality it means they are independent and distinguishable. Physicaly, it means if a qubit is in state $\ket{0}$, the probability of measuring it in state $\ket{1}$ is 0, and vice versa.

Due to these properties, these states form the basis of most quantum algorithms, making them fundamental to understanding quantum computing.

## Outer Product

While the inner product creates a scalar, the outer product creats a matrix. In Dirac notation, the outer product is written as:

\begin{equation}
    \ket{\psi} \bra{\phi}
\end{equation}

If we assume quantum state vectors $\ket{\psi}$ and $\ket{\phi}$:

\begin{align*}
\ket{\psi} =
\begin{bmatrix}
\psi_1 \\
\psi_2
\end{bmatrix}
\end{align*}
    
\begin{align*}
\ket{\phi} =
\begin{bmatrix}
\phi_1 \\
\phi_2
\end{bmatrix}
\end{align*}

Where $\psi_1$ and $\psi_2$ are column vector components of $\ket{\psi}$, and $\phi_1$ and $\phi_2$ are column vector components of $\ket{\phi}$. 

Their outer product is:

\begin{align*}
\ket{\psi} \bra{\phi} =
\begin{bmatrix}
\psi_1 \\
\psi_2
\end{bmatrix}
\begin{bmatrix}
\phi_1^* & \phi_2^*
\end{bmatrix} = 
\begin{bmatrix}
\psi_1 \phi_1^* & \psi_1 \phi_2^*
\\
\psi_2 \phi_1^* & \psi_2 \phi_2^*
\end{bmatrix}
\end{align*}

A matrix acts as a linear operator in quantum mechanics.

In [17]:
# Ket |ψ⟩
ket_psi = np.array([[1 + 2j], [3 + 4j]])

print("Ket |ψ⟩:\n")
print(ket_psi)


Ket |ψ⟩:

[[1.+2.j]
 [3.+4.j]]


In [ ]:
# Ket |φ⟩
ket_phi = np.array([[5 + 6j], [7 + 8j]])

print("Ket |φ⟩:\n")
print(ket_phi)

Ket |φ⟩:

[[5.+6.j]
 [7.+8.j]]


In [21]:
# Compute the outer product |ψ⟩⟨φ|
outer_product = np.dot(ket_psi, ket_phi.conj().T)
print("Outer Product |ψ⟩⟨φ|:\n\n", outer_product)

Outer Product |ψ⟩⟨φ|:

 [[17.+4.j 23.+6.j]
 [39.+2.j 53.+4.j]]


### Outer Product of a State With Itself

If the ket and bra are the same (e.g., $\ket{\psi} \bra{\psi}$), the result is called a density matrix in quantum mechanics. It is used to represent the state of a system.

In [22]:
# Compute the outer product |ψ⟩⟨ψ|
outer_product_with_itself = np.dot(ket_psi, ket_psi.conj().T)
print("Outer Product with Itself |ψ⟩⟨ψ|:\n\n", outer_product_with_itself)

Outer Product with Itself |ψ⟩⟨ψ|:

 [[ 5.+0.j 11.+2.j]
 [11.-2.j 25.+0.j]]


### A Real-World Example: Quantum Projection

In quantum mechanics, the outer product is often used to define projection operators. A projection operator projects a state onto a specific subspace.

If we have a state vector $\ket{\psi}$:

\begin{align*}
\ket{\psi} =
\begin{bmatrix}
\psi_1 \\
\psi_2
\end{bmatrix}
\end{align*}

And a computational basis state $\ket{0}$ :

\begin{align*}
\ket{0} =
\begin{bmatrix}
1 \\
0
\end{bmatrix}
\end{align*}

Projection Operator $P_0$ is:

\begin{align*}
P_0 =
\ket{0} \bra{0}
=
\begin{bmatrix}
1 \\
0
\end{bmatrix}
\begin{bmatrix}
1 & 0
\end{bmatrix} = 
\begin{bmatrix}
1 & 0
\\
0 & 0
\end{bmatrix}
\end{align*}

The projected state $\ket{\psi}'$ can be calculated using:

\begin{align*}
\ket{\psi}' = P_0 \ket{\psi}
\end{align*}

The $\ket{\psi}'$ is aligned with the computational basis state $\ket{0}$. All components of $\ket{\psi}$ orthogonal to $\ket{0}$ are now removed. In quantum mechanics, this technique is used to calculate probabilities of measuring a quantum state in a particular basis.

In [23]:
# Define the computational basis state |0⟩
ket_0 = np.array([[1], [0]])

print("Ket |0⟩:\n")
print(ket_0)

Ket |0⟩:

[[1]
 [0]]


In [24]:
# Compute the projection operator P0 = |0⟩⟨0|
P0 = np.dot(ket_0, ket_0.conj().T)

print("Projection Operator P0:\n")
print(P0)

Projection Operator P0:

[[1 0]
 [0 0]]


In [25]:
# Apply the projection operator to |ψ⟩
projected_psi = np.dot(P0, ket_psi)

print("Projected State |ψ'⟩:\n")
print(projected_psi)

Projected State |ψ'⟩:

[[1.+2.j]
 [0.+0.j]]


In [26]:
# Apply the projection operator to |φ⟩
projected_phi = np.dot(P0, ket_phi)

print("Projected State |φ'⟩:\n")
print(projected_phi)

Projected State |φ'⟩:

[[5.+6.j]
 [0.+0.j]]
